Add Simplified Chinese translation
Taewan-P/gpt_mobile pull request #24
Opened 2024-07-24 02:13 UTC by nightgpt

2024-07-24 08:15 UTC, Taewan-P requested changes

2024-07-24 08:15 UTC, Taewan-P commented on app/src/main/res/values-zh-rCN/strings.xml
> + 大多数模型通常建议改变这个或温度，但不是两者都改变。</string>
There is an extra newline inside this string. Is this intended? 

```suggestion
    <string name="top_p_setting_description">在核心采样中，我们按递减概率顺序计算每个后续令牌的所有选项的累积分布，并在达到该值指定的特定概率后将其截断。\n大多数模型通常建议改变这个或温度，但不是两者都改变。</string>
```
Also, please merge this string resource to one line like the above suggestion. Multiple lines inside strings.xml will not be actually shown as multiple lines in the app.

2024-07-24 10:11 UTC, Taewan-P approved these changes
LGTM

Thanks for the contribution!

2024-07-24 10:12 UTC, merged

2024-07-24 11:08 UTC, nightgpt commented
I just installed the auto-build apk, why is it not displaying Simplified Chinese properly on my device, and still in English?
![Screenshot_20240724190716](https://github.com/user-attachments/assets/9b872b33-2d01-4583-bf00-04f8ff25e5ca)
![Screenshot_20240724190720](https://github.com/user-attachments/assets/3acc8880-fe39-41d9-8c2f-9a101b7611c7)

2024-07-24 11:18 UTC, Taewan-P commented
Check for per-app language setting in your phone setting, or in your app information page. You should be able to change it there.
If your phone uses Android 12 or below, it is not currently supported.

2024-07-24 11:27 UTC, nightgpt commented
My phone language is now Simplified Chinese, but the problem is not resolved
The "所有语言" in the screenshot means all languages, but there is no option for Simplified Chinese.
![Screenshot_20240724192134](https://github.com/user-attachments/assets/274c520d-a6d9-4afd-8082-153e3cb1a924)

2024-07-24 11:30 UTC, nightgpt commented
And I'm on Android 13.

2024-07-24 11:36 UTC, Taewan-P commented
<img width="358" alt="image" src="https://github.com/user-attachments/assets/fe6c1ecb-a20a-4872-a968-1fabb521b071">

From my emulator, after selecting Chinese, choosing the second one on the picture above changes the app language. (Don't know how to read it) Isn't this simplified Chinese? 

<img width="359" alt="image" src="https://github.com/user-attachments/assets/98e1bf03-fa1d-41be-8536-906ff8d1aded">

2024-07-24 11:53 UTC, nightgpt commented
Maybe we're not installing the same apk?
Sorry, it should be my mistake.
My apk was downloaded from this page
https://github.com/Taewan-P/gpt_mobile/actions/runs/10074482557

2024-07-24 11:59 UTC, nightgpt commented
Or maybe it's because I'm using the Chinese version of MIUI.
The Chinese version of MIUI often has some problems

2024-07-24 12:11 UTC, nightgpt commented
I just asked a friend who uses class native android to test the apk for me, so it should be a problem with getting the channel, sorry about that
![5a57bfefed73b0e9](https://github.com/user-attachments/assets/f7653535-a851-472d-84bb-dc233a62002b)

2024-07-25 09:13 UTC, nightgpt commented
> <img alt="image" width="358" src="https://private-user-images.githubusercontent.com/27392567/351697389-fe6c1ecb-a20a-4872-a968-1fabb521b071.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE4OTg5ODIsIm5iZiI6MTcyMTg5ODY4MiwicGF0aCI6Ii8yNzM5MjU2Ny8zNTE2OTczODktZmU2YzFlY2ItYTIwYS00ODcyLWE5NjgtMWZhYmI1MjFiMDcxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI1VDA5MTEyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNhODE3NDE5YzQzYThlMjljOTc0ZGI3YjAyN2M3ZTQyMzZkMzkxZmRkY2FhZTU0OTM0MGMxMWM4NzE0YmE1ZmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.eGg7dceKjl1xhoJzanE7abQP6BOCb4hBn4ng7-nFijc">
> From my emulator, after selecting Chinese, choosing the second one on the picture above changes the app language. (Don't know how to read it) Isn't this simplified Chinese?
> 
> <img alt="image" width="359" src="https://private-user-images.githubusercontent.com/27392567/351697829-98e1bf03-fa1d-41be-8536-906ff8d1aded.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE4OTg5ODIsIm5iZiI6MTcyMTg5ODY4MiwicGF0aCI6Ii8yNzM5MjU2Ny8zNTE2OTc4MjktOThlMWJmMDMtZmExZC00MWJlLTg1MzYtOTA2ZmY4ZDFhZGVkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI1VDA5MTEyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRhYTMyY2IwN2ZiOWJiNWMwYWU4NDlmMDY3Yzc4YjE0YzFlMGM4NzRjY2JkNjU5NzA0M2VkNGJjMzNkMWM3ZWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Ap89ufrmjjnEw40VRwnOf0-oXN9dvWjTbw5Y97NoUlw">

Yes.

2024-07-25 09:25 UTC, Taewan-P commented
Is it solved?

2024-07-25 09:47 UTC, nightgpt commented
> Is it solved?

No

2024-07-25 09:53 UTC, nightgpt commented
Can you send me a copy of the apk file you installed?
I think it's the access channel, you probably built it yourself with the source code, while I downloaded the auto-built apk

2024-07-25 10:14 UTC, Taewan-P commented
Looking at the workflow logs, it built the wrong source code. It should be cloning your forked version, but pulled the origin code. That's why it is not normally applied.

I can't access to my computer right now, so you should try fetching upstream of the fork or pull my repo main branch. Then, try building it on your computer & install.

2024-07-25 10:15 UTC, Taewan-P commented
If you can't build it on your own, I might have time to upload it tonight

2024-07-25 10:31 UTC, nightgpt commented
> Looking at the workflow logs, it built the wrong source code. It should be cloning your forked version, but pulled the origin code. That's why it is not normally applied.
> 
> I can't access to my computer right now, so you should try fetching upstream of the fork or pull my repo main branch. Then, try building it on your computer & install.

OK

2024-07-25 10:32 UTC, nightgpt commented
> Looking at the workflow logs, it built the wrong source code. It should be cloning your forked version, but pulled the origin code. That's why it is not normally applied.
> 
> I can't access to my computer right now, so you should try fetching upstream of the fork or pull my repo main branch. Then, try building it on your computer & install.

Okay

2024-07-25 10:40 UTC, nightgpt commented
> If you can't build it on your own, I might have time to upload it tonight

Thank you

2024-07-25 12:30 UTC, Taewan-P commented
[app-debug.apk.zip](https://github.com/user-attachments/files/16377582/app-debug.apk.zip)

2024-07-25 13:12 UTC, nightgpt commented
> Try this: [app-debug.apk.zip](https://github.com/user-attachments/files/16377582/app-debug.apk.zip)
> 

It’s solved.Thanks!![Screenshot_20240725211113.jpg](https://github.com/user-attachments/assets/da917edd-f5df-4dff-8567-8c23f53a8275)